[package]
name = "setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.18"
toml = "0.8.19"
xdg = "2.5.2"
serde = { version = "1.0", features = ['derive'] }
