[tmux]
src = "./configs/tmux/.tmux.conf"
dst = "~/.tmux.conf"
flag = "tmux"

[zsh]
src = "./configs/zsh/.zshrc"
dst = "~/.zshrc"
flag = "zsh"

[alacritty]
src = "./configs/alacritty"
dst = "~/.config/alacritty"
flag = "alacritty"

[ghostty]
src = "./configs/ghostty"
dst = "~/.config/ghostty"
flag = "ghostty"

[neovim]
src = "./configs/neovim"
dst = "~/.config/nvim/"
flag = "neovim"

[zed_keymaps]
src = "./configs/zed/keymap.json"
dst = "~/.config/zed/keymap.json"
flag = "zed-keymaps"

[zed_settings]
src = "./configs/zed/settings.json"
dst = "~/.config/zed/settings.json"
flag = "zed-settings"

[test]
src = "./configs/test.txt"
dst = "~/.config/test.txt"
flag = "test"

