-- No setup needed for these plugins — they work on load
-- christoomey/vim-tmux-navigator
-- nvim-lua/plenary.nvim
-- tpope/vim-surround
-- tpope/vim-endwise
-- tpope/vim-repeat
-- tpope/vim-sleuth
-- vim-ruby/vim-ruby
-- kchmck/vim-coffee-script
