import = ["~/.config/alacritty/rose-pine/rose-pine-dawn.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.offset]
# x = 0
# y = -5

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
decorations = "full"
dynamic_title = false
startup_mode = "Maximized"

[window.dimensions]
columns = 130
lines = 40
