import = ["/Users/gugulenok/.config/alacritty/rose-pine/rose-pine-dawn.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 19.0

[font.normal]
family = "FantasqueSansM Nerd Font"

[font.offset]
x = 0
y = 5

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
decorations = "full"
dynamic_title = false
startup_mode = "Maximized"

[window.dimensions]
columns = 130
lines = 40

[window.padding]
x = 5
y = 2
