[package]
name = "setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.7.5"
dirs = "5.0.1"
toml = "0.8.19"
serde = { version = "1.0", features = ['derive'] }
